# Data paths
local_data_path: '/mnt/beegfs/sinai-cern/heppy/hep-corpus/v3.0/' # last slash must be added
data_loader_path: '/mnt/beegfs/sinai-cern/heppy/cern-heppy/datasets/heppy/heppy.py'

# Checkpoint paths
default_checkpoint_path: '/mnt/beegfs/sinai-cern/heppy/cern-heppy/models/xlm-roberta-base/'
trained_checkpoints_path: '/mnt/beegfs/sinai-cern/heppy/cern-heppy/checkpoints/full-train/'
warmedup_checkpoints_path: '/mnt/beegfs/sinai-cern/heppy/cern-heppy/checkpoints/warm-up/'
warmedup_checkpoint: 'checkpoint-9040'
trained_checkpoint: 'checkpoint-41584'

# Train/val split ratio
val_split_ratio: 0.2

# Train (True) or Evaluate (False)
fine_tune: False
